Package name:     chimera
Version number:   2.0a19
Original author:  John Kilburg <bug-chimera@cs.unlv.edu>
Original URL:     http://www.cs.unlv.edu/chimera/
HP-UX URL:        http://hpux.connect.org.uk/hppd/cgi-bin/search?package=&term=chimera-
Install tree:     /opt/chimera
Report bugs to:   lavasani@connect.org.uk
Tested on:        HP 9000/780/C160 running HP-UX 11.00
C compiler used:  Version A.11.01.03
Purpose:
This is an X/Athena Web client. If you do not know about the Web then read the
comp.infosystems.www newsgroup or grab the FAQ from rtfm.mit.edu using ftp.
Like Mosaic it will format and display HTML Hypertext documents. Chimera uses
less memory than Mosaic but it is not quite so pretty!! Thats the trade off!
Date archived:    Mon 15 May 2000

-------------------------------------------------------------------------------

Added

	Path to Xaw and Xmu include files.

Compile:

	Edit "Common.tmpl" and define the directory you want to install the
	package. Also set any other path is need for your site.

	xmkmf
	make Makefiles
	make
	make install

Run:

	chimera

Archived:

Mahdi Lavasani
lavasani@csc.liv.ac.uk
