.TH chimera 1 "26 October 1994"
.IX chimera

.SH NAME
chimera - X/Athena World-Wide Web Client

.SH SYNOPSIS
.B chimera
.RI [ URL ]

.SH DESCRIPTION
Chimera is a program which allows a user to access World-Wide Web servers
and other information servers.  It presents the user with a point-and-click
graphical interface using the X Window System and the Athena Widgets.

.SH COMMAND LINE
A single URL can be specified on the command line for indicating the
initial Chimera document.

The usual Xt options like geometry can also be specified on the command
line.

.SH RESOURCES
The following resources are Chimera specific resources:

.IP "\fBhomeURL\fP"
This string is used to specify the URL for the page displayed by default
when chimera is first started.  The default is defined at compile time.

.SH "SEE ALSO"
lynx(1), Mosaic(1), netscape(1)

.SH "BUGS"
Zillions for sure.
This man page is really old, possibly wrong, and not even close to complete.

.SH AUTHOR
Copyright 1993, 1994, 1995 by John Kilburg (john@cs.unlv.edu)
